name: Auto Tag on PR Merge to Main
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get source branch name
        id: get_branch_name
        run: |
          SOURCE_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/refs\/heads\///')
          echo "Source branch: $SOURCE_BRANCH"
          echo "tag_name=$SOURCE_BRANCH" >> $GITHUB_OUTPUT # Set an output variable for later steps
      - name: Create Git tag
        run: |
          TAG_NAME="${{ steps.get_branch_name.outputs.tag_name }}"
          echo "Attempting to create tag: $TAG_NAME"
          git config user.name "github-actions[bot]" # Configure Git user for the commit
          git config user.email "github-actions[bot]@users.noreply.github.com" # Configure Git email
          git tag $TAG_NAME # Create the tag

      - name: Push Git tag
        run: |
          TAG_NAME="${{ steps.get_branch_name.outputs.tag_name }}"
          echo "Pushing tag: $TAG_NAME"
          git push origin $TAG_NAME # Push the tag to origin
